// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AppQuery is the predicate function for appquery builders.
type AppQuery func(*sql.Selector)

// AppResponse is the predicate function for appresponse builders.
type AppResponse func(*sql.Selector)

// IP is the predicate function for ip builders.
type IP func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
