// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sujithshajee/dnsbl/app/ent/appquery"
	"github.com/sujithshajee/dnsbl/app/ent/predicate"
)

// AppQueryDelete is the builder for deleting a AppQuery entity.
type AppQueryDelete struct {
	config
	hooks    []Hook
	mutation *AppQueryMutation
}

// Where appends a list predicates to the AppQueryDelete builder.
func (aqd *AppQueryDelete) Where(ps ...predicate.AppQuery) *AppQueryDelete {
	aqd.mutation.Where(ps...)
	return aqd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (aqd *AppQueryDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(aqd.hooks) == 0 {
		affected, err = aqd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AppQueryMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			aqd.mutation = mutation
			affected, err = aqd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(aqd.hooks) - 1; i >= 0; i-- {
			if aqd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = aqd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, aqd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (aqd *AppQueryDelete) ExecX(ctx context.Context) int {
	n, err := aqd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (aqd *AppQueryDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: appquery.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: appquery.FieldID,
			},
		},
	}
	if ps := aqd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, aqd.driver, _spec)
}

// AppQueryDeleteOne is the builder for deleting a single AppQuery entity.
type AppQueryDeleteOne struct {
	aqd *AppQueryDelete
}

// Exec executes the deletion query.
func (aqdo *AppQueryDeleteOne) Exec(ctx context.Context) error {
	n, err := aqdo.aqd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{appquery.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (aqdo *AppQueryDeleteOne) ExecX(ctx context.Context) {
	aqdo.aqd.ExecX(ctx)
}
