// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/sujithshajee/dnsbl/app/ent/appquery"
	"github.com/sujithshajee/dnsbl/app/ent/appresponse"
	"github.com/sujithshajee/dnsbl/app/ent/ip"
	"github.com/sujithshajee/dnsbl/app/ent/schema"
	"github.com/sujithshajee/dnsbl/app/ent/task"
	"github.com/sujithshajee/dnsbl/app/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appqueryMixin := schema.AppQuery{}.Mixin()
	appqueryMixinFields0 := appqueryMixin[0].Fields()
	_ = appqueryMixinFields0
	appqueryMixinFields1 := appqueryMixin[1].Fields()
	_ = appqueryMixinFields1
	appqueryFields := schema.AppQuery{}.Fields()
	_ = appqueryFields
	// appqueryDescCreatedAt is the schema descriptor for created_at field.
	appqueryDescCreatedAt := appqueryMixinFields1[0].Descriptor()
	// appquery.DefaultCreatedAt holds the default value on creation for the created_at field.
	appquery.DefaultCreatedAt = appqueryDescCreatedAt.Default.(func() time.Time)
	// appqueryDescUpdatedAt is the schema descriptor for updated_at field.
	appqueryDescUpdatedAt := appqueryMixinFields1[1].Descriptor()
	// appquery.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appquery.DefaultUpdatedAt = appqueryDescUpdatedAt.Default.(func() time.Time)
	// appquery.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appquery.UpdateDefaultUpdatedAt = appqueryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appqueryDescID is the schema descriptor for id field.
	appqueryDescID := appqueryMixinFields0[0].Descriptor()
	// appquery.DefaultID holds the default value on creation for the id field.
	appquery.DefaultID = appqueryDescID.Default.(func() uuid.UUID)
	appresponseMixin := schema.AppResponse{}.Mixin()
	appresponseMixinFields0 := appresponseMixin[0].Fields()
	_ = appresponseMixinFields0
	appresponseMixinFields1 := appresponseMixin[1].Fields()
	_ = appresponseMixinFields1
	appresponseFields := schema.AppResponse{}.Fields()
	_ = appresponseFields
	// appresponseDescCreatedAt is the schema descriptor for created_at field.
	appresponseDescCreatedAt := appresponseMixinFields1[0].Descriptor()
	// appresponse.DefaultCreatedAt holds the default value on creation for the created_at field.
	appresponse.DefaultCreatedAt = appresponseDescCreatedAt.Default.(func() time.Time)
	// appresponseDescUpdatedAt is the schema descriptor for updated_at field.
	appresponseDescUpdatedAt := appresponseMixinFields1[1].Descriptor()
	// appresponse.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appresponse.DefaultUpdatedAt = appresponseDescUpdatedAt.Default.(func() time.Time)
	// appresponse.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appresponse.UpdateDefaultUpdatedAt = appresponseDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appresponseDescID is the schema descriptor for id field.
	appresponseDescID := appresponseMixinFields0[0].Descriptor()
	// appresponse.DefaultID holds the default value on creation for the id field.
	appresponse.DefaultID = appresponseDescID.Default.(func() uuid.UUID)
	ipMixin := schema.IP{}.Mixin()
	ipMixinFields0 := ipMixin[0].Fields()
	_ = ipMixinFields0
	ipMixinFields1 := ipMixin[1].Fields()
	_ = ipMixinFields1
	ipFields := schema.IP{}.Fields()
	_ = ipFields
	// ipDescCreatedAt is the schema descriptor for created_at field.
	ipDescCreatedAt := ipMixinFields1[0].Descriptor()
	// ip.DefaultCreatedAt holds the default value on creation for the created_at field.
	ip.DefaultCreatedAt = ipDescCreatedAt.Default.(func() time.Time)
	// ipDescUpdatedAt is the schema descriptor for updated_at field.
	ipDescUpdatedAt := ipMixinFields1[1].Descriptor()
	// ip.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ip.DefaultUpdatedAt = ipDescUpdatedAt.Default.(func() time.Time)
	// ip.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ip.UpdateDefaultUpdatedAt = ipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// ipDescID is the schema descriptor for id field.
	ipDescID := ipMixinFields0[0].Descriptor()
	// ip.DefaultID holds the default value on creation for the id field.
	ip.DefaultID = ipDescID.Default.(func() uuid.UUID)
	taskMixin := schema.Task{}.Mixin()
	taskMixinFields0 := taskMixin[0].Fields()
	_ = taskMixinFields0
	taskMixinFields1 := taskMixin[1].Fields()
	_ = taskMixinFields1
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskMixinFields1[0].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskMixinFields1[1].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskMixinFields0[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userMixinFields1 := userMixin[1].Fields()
	_ = userMixinFields1
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields1[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields1[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userMixinFields0[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
