// Code generated by entc, DO NOT EDIT.

package appresponse

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the appresponse type in the database.
	Label = "app_response"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldResponsecode holds the string denoting the responsecode field in the database.
	FieldResponsecode = "responsecode"
	// FieldCodedescription holds the string denoting the codedescription field in the database.
	FieldCodedescription = "codedescription"
	// EdgeQuery holds the string denoting the query edge name in mutations.
	EdgeQuery = "query"
	// Table holds the table name of the appresponse in the database.
	Table = "app_responses"
	// QueryTable is the table that holds the query relation/edge.
	QueryTable = "app_responses"
	// QueryInverseTable is the table name for the AppQuery entity.
	// It exists in this package in order to avoid circular dependency with the "appquery" package.
	QueryInverseTable = "app_queries"
	// QueryColumn is the table column denoting the query relation/edge.
	QueryColumn = "app_query_responses"
)

// Columns holds all SQL columns for appresponse fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldResponsecode,
	FieldCodedescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "app_responses"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"app_query_responses",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
