// Code generated by entc, DO NOT EDIT.

package appquery

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the appquery type in the database.
	Label = "app_query"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeResponses holds the string denoting the responses edge name in mutations.
	EdgeResponses = "responses"
	// EdgeIpaddress holds the string denoting the ipaddress edge name in mutations.
	EdgeIpaddress = "ipaddress"
	// Table holds the table name of the appquery in the database.
	Table = "app_queries"
	// ResponsesTable is the table that holds the responses relation/edge.
	ResponsesTable = "app_responses"
	// ResponsesInverseTable is the table name for the AppResponse entity.
	// It exists in this package in order to avoid circular dependency with the "appresponse" package.
	ResponsesInverseTable = "app_responses"
	// ResponsesColumn is the table column denoting the responses relation/edge.
	ResponsesColumn = "app_query_responses"
	// IpaddressTable is the table that holds the ipaddress relation/edge.
	IpaddressTable = "app_queries"
	// IpaddressInverseTable is the table name for the IP entity.
	// It exists in this package in order to avoid circular dependency with the "ip" package.
	IpaddressInverseTable = "ips"
	// IpaddressColumn is the table column denoting the ipaddress relation/edge.
	IpaddressColumn = "ip_queries"
)

// Columns holds all SQL columns for appquery fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "app_queries"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"ip_queries",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
